export const SEARCH_RESULTS = 'SEARCH RESULTS';
export const SEARCH_LOADING_DONE = 'SEARCH LOADING DONE';
export const SEARCH_LOADING_STARTED = 'SEARCH LOADING STARTED';
export const STORE_CHANNELS = 'STORE CHANNELS';
export const CHANNEL_MOUNTED = 'CHANNEL MOUNTED';
export const CHANNEL_UNMOUNTED = 'CHANNEL UNMOUNTED';

