export const SEARCH_RESULTS = 'SEARCH RESULTS';
export const SEARCH_LOADING_DONE = 'SEARCH LOADING DONE';
export const SEARCH_LOADING_STARTED = 'SEARCH LOADING STARTED';
export const STORE_CHANNELS = 'STORE CHANNELS';
export const CHANNEL_MOUNTED = 'CHANNEL MOUNTED';
export const CHANNEL_UNMOUNTED = 'CHANNEL UNMOUNTED';
export const UNREAD_ALERTS_COUNT = 'UNREAD ALERTS COUNT';
export const NEW_TAB = 'NEW TAB';
export const APPEND_POSTS = 'APPEND POSTS';

export const HOTTEST_TAB = 'HOTTEST TAB';
export const FOLLOWED_TAB = 'FOLLOWED TAB';
export const LATEST_TAB = 'LATEST TAB';
export const PARTICIPATED_TAB = 'PARTICIPATED TAB';

