export const SEARCH_RESULTS = 'SEARCH RESULTS';
export const SEARCH_LOADING_DONE = 'SEARCH LOADING DONE';
export const SEARCH_LOADING_STARTED = 'SEARCH LOADING STARTED';
export const STORE_CHANNELS = 'STORE CHANNELS';
export const CHANNEL_MOUNTED = 'CHANNEL MOUNTED';
export const CHANNEL_UNMOUNTED = 'CHANNEL UNMOUNTED';
export const UNREAD_ALERTS_COUNT = 'UNREAD ALERTS COUNT';
export const NEW_TAB = 'NEW TAB';
export const APPEND_POSTS = 'APPEND POSTS';

export const HOTTEST_TAB = 'HOTTEST TAB';
export const FOLLOWED_TAB = 'FOLLOWED TAB';
export const LATEST_TAB = 'LATEST TAB';
export const PARTICIPATED_TAB = 'PARTICIPATED TAB';

export const APPEND_ALERTS = 'APPEND ALERTS';

export const SET_TOKEN_USERNAME = 'SET TOKEN USERNAME'

export const ADD_POST = 'ADD POST'

export const OPEN_MODAL = 'OPEN MODAL'
export const CLOSE_MODAL = 'CLOSE MODAL'

export const APPEND_CHANNEL_POSTS = 'APPEND CHANNEL POSTS'
export const CLEAR_CHANNEL_POSTS = 'CLEAR CHANNEL POSTS'
export const CHANNEL_HOLD_ON = 'CHANNEL HOLD ON'
