# Generated by Django 3.0.1 on 2020-01-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
