# Generated by Django 3.0.2 on 2020-02-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channelName',
            field=models.CharField(default='science things', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postTitle',
            field=models.CharField(default='some click bate title', max_length=50),
            preserve_default=False,
        ),
    ]
