# Generated by Django 3.0.1 on 2020-02-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200203_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='supComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subComments', to='mainApp.Comment'),
        ),
    ]
