# Generated by Django 3.0.1 on 2020-01-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200130_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='supComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Comment'),
        ),
    ]
