# Generated by Django 3.0.1 on 2020-02-06 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_auto_20200205_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='blockedUsers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
