# Generated by Django 3.0.1 on 2020-01-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200130_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelinfo',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
