# Generated by Django 3.0.1 on 2020-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_profileinfo_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='followingsNum',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='followingsNum',
            field=models.IntegerField(default=0),
        ),
    ]
