# Generated by Django 3.0.1 on 2020-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200207_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='image',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
